version: '3.8'

services:
  mongodb:
    build:
      context: ./docker
      dockerfile: Dockerfile.mongodb
    container_name: switch-this-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./src/data:/src/data:ro
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./docker/seed-data.sh:/docker-entrypoint-initdb.d/seed-data.sh:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=switch-this
    command: mongod --auth

volumes:
  mongodb_data: 