version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: switch-this-mongodb
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongodb_data:/data/db
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./docker/seed-all-data.js:/docker-entrypoint-initdb.d/seed-all-data.js:ro
      - ./src/data:/src/data:ro

volumes:
  mongodb_data: 