name: Defect Report
description: File a defect/bug report
title: "[Defect]: "
labels: ["defect"]
body:
  - type: markdown
    attributes:
      value: |
        # Switch This Defect Report
        Thanks for taking the time to fill out this defect report!
        
        Please provide as much detail as possible to help us reproduce and fix the issue.
  
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: What part of the application is affected?
      options:
        - Rolling Stock
        - Industry
        - Location
        - Train Route
        - Switchlist
        - Layout State
        - UI/Interface
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severely does this issue affect usage?
      options:
        - Critical (Application crashes or is unusable)
        - Major (Significant functionality is impaired)
        - Normal (Standard defect with workarounds)
        - Minor (Cosmetic or minimal impact)
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Describe the defect
      description: What happened? What did you expect to happen?
      placeholder: |
        Example: When trying to add a new rail car to a track, I received an error message saying "Track is at maximum capacity" even though the track was empty.
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Provide detailed steps to reproduce the issue
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: What browser, device, or environment were you using?
      placeholder: |
        - Browser: [e.g. Chrome 91, Safari 14]
        - Device: [e.g. Desktop, iPhone 12]
        - Operating System: [e.g. Windows 10, macOS Big Sur]
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here
      placeholder: |
        Example: This only happens when I have more than 5 industries defined.
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: You can attach images by clicking this area to highlight it and then dragging files in.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our contributor guidelines
      options:
        - label: I've checked for duplicate issues and verified this is a new defect
          required: true
        - label: I've included all information necessary to reproduce the issue
          required: true 