name: Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  code-quality:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run ESLint
        run: npm run lint
        
      - name: Run TypeScript type check
        run: npx tsc --noEmit
      
      - name: Find duplicate code
        run: npx jsinspect ./src --threshold 30 --identifiers --ignore "node_modules" || true
      
      - name: Run security audit
        run: npm audit --production
      
      - name: Generate bundle analysis
        run: |
          npm install -g next-bundle-analyzer
          ANALYZE=true npm run build
        continue-on-error: true
      
      - name: Upload bundle analysis
        uses: actions/upload-artifact@v4
        with:
          name: bundle-analysis
          path: .next/analyze
          retention-days: 14
        continue-on-error: true 