name: Dependency Updates

on:
  schedule:
    - cron: '0 0 * * 1' # Run weekly on Mondays
  workflow_dispatch: # Allow manual triggering

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Update dependencies
        run: |
          npm outdated
          npx npm-check-updates -u
          npm install
      
      - name: Run tests to verify updates
        run: npm test
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: '[c] Update dependencies'
          title: '[c] Update dependencies'
          body: |
            This PR updates dependencies to their latest versions.
            
            - Automated dependency update
            - Please review and test thoroughly before merging
          branch: dependency-updates
          base: main
          labels: dependencies 