name: Run Tests

on:
  # Run on push to any branch
  push:
    branches: ['**']
  
  # Allow manual triggering from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Verify lucide-react installation
        run: npm install lucide-react --no-save
      
      - name: Build project
        run: npm run build
      
      - name: Run linting
        run: npm run lint
      
      - name: Run tests with coverage
        run: npm run test:ci
      
      - name: Generate coverage report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/cobertura-coverage.xml
          badge: true
          format: markdown
          output: both
      
      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          header: test-coverage
          recreate: true
          path: code-coverage-results.md
      
      - name: Write to Job Summary
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
      
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: coverage/
          retention-days: 14
      
      - name: Create Coverage Summary JSON
        if: github.ref == 'refs/heads/main'
        run: |
          mkdir -p coverage-summary
          cp coverage/coverage-summary.json coverage-summary/coverage.json
      
      - name: Deploy Coverage Summary
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./coverage-summary
          publish_branch: coverage-summary
          force_orphan: true 